apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apiproducts-apikey-portalauth
  namespace: gloo-system
spec:
  configs:
    - name: tracksAuth
      portalAuth:
        url: http://gateway-portal-web-server.gloo-system.svc.cluster.local:8080
        cacheDuration: 10s
        apiKeyHeader: "api-key"