apiVersion: enterprise.gloo.solo.io/v1
kind: AuthConfig
metadata:
  name: apiproducts-atv-portalauth
  namespace: gloo-system
spec:
  configs:
    - name: oauth2
      oauth2:
        accessTokenValidation:
          jwt:
            remoteJwks:
              url: http://keycloak.example.com/realms/portal-mgmt/protocol/openid-connect/certs
    - name: tracksAuth
      portalAuth:
        url: http://gateway-portal-web-server.gloo-system.svc.cluster.local:8080
        redisOptions:
          host: redis:6379
    
    # - name: opa
    #   opaAuth:
    #     modules:
    #       - name: apis
    #         namespace: gloo-system
    #     query: "data.test.result"