apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-portal-web-server-2
  namespace: gloo-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gateway-portal-web-server-2
      gloo-mesh: gloo-mesh-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app.kubernetes.io/name: gateway-portal-web-server
      creationTimestamp: null
      labels:
        app: gateway-portal-web-server-2
        gloo-mesh: gloo-mesh-portal
    spec:
      containers:
      - args:
        - --dev-logger=false
        - --verbose=false
        - --http-port=8080
        - --database=postgres
        - --idp-server-url=http://idp-connect.gloo-system.svc.cluster.local
        - --api-key-secret-path=/etc/apikey/secret
        env:
        - name: K8S_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              divisor: "1"
              resource: limits.memory
        image: quay.io/solo-io/gateway-portal-web-server-ee:1.18.4
        imagePullPolicy: IfNotPresent
        name: gateway-portal-web-server
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/apikey
          name: apikey-secret
          readOnly: true
        - mountPath: /etc/database
          name: database
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: gateway-portal-web-server
      serviceAccountName: gateway-portal-web-server
      terminationGracePeriodSeconds: 30
      volumes:
      - name: apikey-secret
        secret:
          defaultMode: 420
          optional: true
          secretName: portal-apikey-secret
      - name: database
        secret:
          defaultMode: 420
          optional: true
          secretName: portal-database-config
