apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: gloo-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: dpage/pgadmin4:latest
          ports:
            - containerPort: 80
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "user@email.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "pass"
          volumeMounts:
            - name: pgadmin-config-volume
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
      volumes:
        - name: pgadmin-config-volume
          configMap:
            name: pgadmin-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: gloo-system
spec:
  type: ClusterIP
  ports:
    - port: 30002
      targetPort: 80
  selector:
    app: pgadmin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: gloo-system
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Portal DB",
          "Group": "Servers",
          "Host": "postgres.gloo-system.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "db",
          "Username": "user",
          "Password": "pass",
          "SSLMode": "disable",
          "Comment": "Automatically added server"
        }
      }
    }